# Generated by Django 5.0 on 2023-12-20 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Debt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('type', models.IntegerField(choices=[(0, 'Factory'), (1, 'Retail'), (2, 'Entrepreneur')], verbose_name='Type')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networks.tradelink', verbose_name='Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('product_launch_date', models.DateTimeField(verbose_name='Product Launch Date')),
                ('suppliers', models.ManyToManyField(related_name='products', to='networks.tradelink', verbose_name='Suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('house_number', models.CharField(max_length=20, verbose_name='House Number')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networks.tradelink', verbose_name='Organization')),
            ],
        ),
    ]
